#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 11 09:35:24 2020

@author: le
"""
__author__    = "Van-Huong Le (levanhuong15011989@gmail.com)"
__date__      = "2020-06-09"
__copyright__ = "Copyright (C) Van-Huong Le"
__license__   = "GNU GPL Version 3.0"
